FROM python:3.10-alpine
WORKDIR /backend

COPY ./backend /backend
COPY ./backend/requirements.txt /backend
COPY .env /backend/.env

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3"]
CMD ["app.py"]