version: '3'
services:
  db:
    container_name: mysql
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/allergy.sql:/vol/allergy.sql
      - ./mysql/data:/var/lib/mysql
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    stop_signal: SIGINT
    ports:
      - 5000:5000
    depends_on:
      - db
  nginx:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # image: nginx:stable-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend